version: "3"
services:
  mongo:
    container_name: mongo-fintech
    image: mongo:latest
    restart: always
    ports:
      - 27018:27018
    environment: 
      - MONGO_INITDB_DATABASE=$MONGO_DBNAME
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
  backend:
    container_name: backend_fintech
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/app/src
    environment: 
      - MONGO_URL=$MONGO_URL